const types = Object.freeze({
    //ToDo
    SET_TASKS: "SET_TASKS",
    TOGGLE_LOADING: "TOGGLE_LOADING",
    DELETE_ONE_TASK: "DELETE_ONE_TASK",
    ADD_TASK: "ADD_TASK",
    EDIT_TASK: "EDIT_TASK",
    TOGGLE_SEELECT_TASK: "TOGGLE_SEELECT_TASK",
    DELETE_SELECT_TASKS: "DELETE_SELECT_TASKS",
    TOGGLE_SELECT_ALL_TASKS: "TOGGLE_SELECT_ALL_TASKS",
    TOOGLE_OPEN_ADD_TASK_MODAL: "TOOGLE_OPEN_ADD_TASK_MODAL",
    TOGGLE_OPEN_DELETE_MODAL: "TOGGLE_OPEN_DELETE_MODAL",
    TOOGLE_CLOSE_TASK_MODAL: "TOOGLE_CLOSE_ADD_TASK_MODAL",
    TOOGLE_OPEN_EDIT_TASK_MODAL: "TOOGLE_OPEN_EDIT_TASK_MODAL",

    //contact

    ADD_CONTACT: "ADD_CONTACT",
    CONTACT_ERROR: "CONTACT_ERROR",
    CONTACT_STATE_RESET: "CONTACT_STATE_RESET"

});
export default types;